language: node_js
node_js:
  - "9"
before_install:
  - sudo apt-get install -y libblocksruntime-dev uthash-dev libgc-dev
install:
  - npm install
  - ./node_modules/.bin/bower install
script:
  - npm run build
  - make test
